# Generated by Django 4.2.4 on 2023-08-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=70)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('published_year', models.IntegerField(default=2023)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
